import os
import sys

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from datetime import date
import streamlit as st
import requests
from core import ai_coach

API_URL = 'http://127.0.0.1:8000/habits'

def main():
    st.title("Habit tracker")
    title = st.text_input("input your habit")
    complete = st.date_input("input date, when you want to finish")
    button = st.button("confirm")
    
    
    if button:
        if not len(title) > 0:
            st.error('you don\'t input title')
        else: 
            formatted_date = complete.strftime("%Y-%m-%d")
            payload = {
                'title': title,
                "complete": formatted_date,
            }
            
            response = requests.post(API_URL, json=payload)
            
            if response.status_code == 201:
                st.success(f"Habit {title} added")
            else: st.error(f"Somethig went wrong and habbit isn't added")
            
    st.divider()
    st.header("current habits")
    response = requests.get(API_URL)
    if response.status_code == 200:
        habits_list = response.json()
        for i in habits_list:
            col1, col2, col3 = st.columns([6, 1, 1])
            with col1:
                st.write(f"**{i['title']}**— to {i['complete']}")
                st.write(f"current strike— {i['current_strike']}")
                st.write(f"max strike— {i['max_strike']}")
            
            with col2:
                if st.button("✅", key=f"upd_{i['id']}"):
                    UPDATE_URL = f"{API_URL}/{i['id']}"
                    update_response = requests.patch(UPDATE_URL)
                    
                    if update_response.status_code == 200:
                        st.success(f"complete {date.today().strftime('%Y-%m-%d')}")
                        st.rerun()  
                    else: st.error("Something went wrong and system can not finish habit")
                    
            with col3: 
                if st.button("🗑️", key=f"del_{i['id']}"):
                    DELETE_URL= f"{API_URL}/{i['id']}"
                    delete_response= requests.delete(DELETE_URL)
                    
                    if delete_response.status_code == 204:
                        st.success("Deleted!")
                        st.rerun()
                    else:
                        st.error('somethig went wrong and system can not delete habit')
                        
    st.divider()
    st.header("AI analyze")
    st.write("do you want to have A_ tip? Push button, and we give you message, generated by Google Gemini©")
    ai_button = st.button("generate tip")
    if ai_button:
        with st.spinner("AI analyze your habbits"):
            try:
                response = requests.get(API_URL)
                habits_list = response.json()
                ai_response = ai_coach.get_ai_advice(habits_list)
                st.write(ai_response)

            except Exception as e:
                st.error(f"Something went wrong with AI: {e}")
        
        
                 
                     
if __name__ == "__main__":
    main() 